[TST] Test sanitize_label()
nipy/heudiconv pull request #579
Opened 2022-07-15 14:44 UTC by l-espana

Hoping this keeps previous code and commits!

2022-07-15 14:59 UTC, yarikoptic requested changes
This is much better!  

- left instructions on testing
- since PR is old, conflicts with master piled up, this branch should merge our `master` and resolve conflicts (or rebase -- could be a bit more "involved").  if need help -- I can do that after testing fixed up etc.

2022-07-15 14:59 UTC, yarikoptic commented on heudiconv/tests/test_bids.py
> +def sanitize_label():
```suggestion
def test_sanitize_label():
```

2022-07-15 15:00 UTC, yarikoptic commented
I still have no clue what is wrong with travis CI, and why appveyor kicked in (we don't use it here AFAIK)... later

2022-07-19 20:39 UTC, yarikoptic commented on heudiconv/bids.py
> +<<<<<<< HEAD
remove conflict markers/resolve conflicts here and elsewhere

2022-07-19 20:39 UTC, yarikoptic commented on heudiconv/bids.py
> +>>>>>>> refactor convert_sid_bids to sanitize_label
smells like some incorrectly resolved conflict

2022-07-20 12:12 UTC, l-espana commented on heudiconv/tests/test_bids.py
> +        #this should also raise an error for an empty value
Oh, I think I see what you mean. Will update.

2022-12-29 15:02 UTC, closed without merging