Refactor create_seqinfo tiny bit to avoid duplication and add logging; and in tests to reuse list of dicom paths
nipy/heudiconv pull request #785
Opened 2024-09-16 17:20 UTC by yarikoptic

Follow up to
- #753 
triggered by desire to avoid "growing" duplication and wanting to avoid call outs to `wrapper_from_file` at the test module import time.

2024-09-24 14:57 UTC, bpinsard requested changes
apart from missing typing, LGTM

2024-09-24 14:57 UTC, bpinsard commented on heudiconv/tests/test_dicoms.py
> +    dcmfile,
```suggestion
    dcmfile: str,
```

2024-09-24 14:57 UTC, bpinsard commented on heudiconv/tests/test_dicoms.py
> +def test_get_reproducible_int(dcmfile) -> None:
```suggestion
def test_get_reproducible_int(dcmfile:str) -> None:
```

2024-10-01 13:10 UTC, bpinsard approved these changes

2024-10-01 15:13 UTC, yarikoptic commented on heudiconv/tests/test_dicoms.py
> +def test_get_reproducible_int(dcmfile:str) -> None:
```suggestion
def test_get_reproducible_int(dcmfile: str) -> None:
```
lint

2024-10-01 15:27 UTC, merged