[ENH] filter dicoms earlier to avoid nibabel crash with XA ill-formed mutli-planar localizer dicoms
nipy/heudiconv pull request #806
Opened 2024-11-29 21:04 UTC by bpinsard

see https://github.com/nipy/nibabel/issues/1392#issuecomment-2508066687

Apparently some of the validation of the dicom triggers nibabel.nicom that crashes on ill-formed dicoms.
Moving the dicom filter a bit before, allow to easily filter these with the heuristics `filter_dicom`. 
I should not change anything to the results.

2025-08-22 20:31 UTC, dangom commented
Affected by this as well. Any change this could be merged?!

2025-08-26 19:46 UTC, hbraunDSP commented
I am also affected by this; adding my voice to the merge requests.

Are we waiting on test coverage?

2025-08-29 21:41 UTC, yarikoptic requested changes
Thanks for the PR! Sorry it takes awhile to get to them.

I left some questions to clarify the changes.  Also I wonder if there is an easy way for a test, even if it would just be a smoke test to show that it crashed before and no longer? ;)

2025-08-29 21:41 UTC, yarikoptic commented on heudiconv/heuristics/reproin.py
> +    return True if dcmdata.get("StudyInstanceUID") in dicoms2skip else False
why this change was necessary?  (the others in the file are just formatting, and should not be needed)

2025-08-29 21:41 UTC, yarikoptic commented on heudiconv/dicoms.py
> +        return None
I am a little confused -- it seems that you moved filtering **later** not earlier!

I do see that you made it so it clears/deletes signatures now **later** than filtering is done, so would that suffice -- just to move deletion of signatures and keeping the rest of the code as is?

2025-09-02 15:24 UTC, bpinsard commented on heudiconv/dicoms.py
> +        return None
Yes, you're right, the main issue was while deleting signature on malformed dicoms. I reset the position of the call to filter dicoms and reverted the heuristics change that was no longer required.

2025-09-02 19:39 UTC, merged